// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels;

#nullable disable

namespace Tierhandlung_WPF_Anwendung_mit_Entity_Framework.Migrations
{
    [DbContext(typeof(TierheimContext))]
    [Migration("20260219183248_AddNewFields")]
    partial class AddNewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Account", b =>
                {
                    b.Property<int>("NutzerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Nutzer_ID");

                    b.Property<string>("Benutzername")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ADMIN");

                    b.Property<string>("Passwort")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("NutzerId")
                        .HasName("PK__Account__34A15DAD78B473E6");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Anfragen", b =>
                {
                    b.Property<int>("AnfrageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Anfrage_ID");

                    b.Property<int?>("NutzerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Nutzer_ID");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextInfo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tier_ID");

                    b.HasKey("AnfrageId")
                        .HasName("PK__Anfragen__CB00C311EB80294A");

                    b.HasIndex("NutzerId");

                    b.HasIndex("TierId");

                    b.ToTable("Anfragen");
                });

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Tiere", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tier_ID");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Geburtsdatum")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("BLOB");

                    b.Property<string>("Tierart")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tiername")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("TierId")
                        .HasName("PK__Tiere__754A1AE3A57B0B9A");

                    b.ToTable("Tiere");
                });

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Anfragen", b =>
                {
                    b.HasOne("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Account", "Nutzer")
                        .WithMany("Anfragen")
                        .HasForeignKey("NutzerId")
                        .HasConstraintName("FK__Anfragen__Nutzer__3B75D760");

                    b.HasOne("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Tiere", "Tier")
                        .WithMany("Anfragen")
                        .HasForeignKey("TierId")
                        .HasConstraintName("FK__Anfragen__Tier_I__3C69FB99");

                    b.Navigation("Nutzer");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Account", b =>
                {
                    b.Navigation("Anfragen");
                });

            modelBuilder.Entity("Tierhandlung_WPF_Anwendung_mit_Entity_Framework.DbModels.Tiere", b =>
                {
                    b.Navigation("Anfragen");
                });
#pragma warning restore 612, 618
        }
    }
}
